const ACTIONS = {
    SIDE_MENU: 'SIDE_MENU',
    CLOSE_SIDE_MENU: 'CLOSE_SIDE_MENU',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
    USER_LOADING: 'USER_LOADING'
};

module.exports = {
    ACTIONS
}